version: "3.8"

services:
  mcp-server:
    container_name: perplexity-mcp-server
    build:
      context: ./perplexity-mcp-server # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # Pass the API key from the .env file
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      # Pass PORT if needed, though default is 8080 in index.ts
      # - PORT=8080
    # Restart policy (optional, good for dev)
    restart: unless-stopped

  backend:
    container_name: backend-container # Optional: explicit name
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    environment:
      # --- Crucial for communication inside Docker network ---
      - MCP_PERPLEXITY_SSE_URL=http://mcp-server:8080/sse # Use service name 'mcp-server'
      # --- Pass secrets and config from .env file ---
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_HOST=${PINECONE_INDEX_HOST}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Optional config vars (uncomment if needed and set in .env)
      # - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL}
      # - OPENAI_SYNTHESIS_MODEL=${OPENAI_SYNTHESIS_MODEL}
      # - ANTHROPIC_TOOL_SELECTION_MODEL=${ANTHROPIC_TOOL_SELECTION_MODEL}
    depends_on:
      - mcp-server # Ensures mcp-server starts before backend
    # Restart policy (optional)
    restart: unless-stopped
# Docker Compose automatically creates a default network for these services
